### ISSUE TITLE
Does not work on Paper version 1.21.9

### ISSUE THREAD

**Issue by BogdanKas2015** [LOOHP/ImageFrame#136]
Here is the error code:
12:56:52] [Server thread/INFO]: [ImageFrame] Enabling ImageFrame v1.8.7.0
[12:56:53] [Server thread/INFO]: [ImageFrame] ImageFrame has hooked into ViaVersion!
[12:56:57] [Server thread/ERROR]: Error occurred while enabling ImageFrame v1.8.7.0 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_21_R6/inventory/CraftItemStack
	at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:534) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:513) ~[?:?]
	at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.forName(AbstractDefaultRulesReflectionProxy.java:68) ~[reflection-rewriter-runtime-0.0.3.jar:?]
	at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.forName(Unknown Source) ~[paper-1.21.9.jar:1.21.9-38-27f926e]
	at ImageFrame-1.8.7.0.jar/com.loohp.imageframe.nms.NMS.getInstance(NMS.java:37) ~[ImageFrame-1.8.7.0.jar:?]
	at ImageFrame-1.8.7.0.jar/com.loohp.imageframe.invisibleframe.InvisibleFrameManager.withInvisibleItemFrameData(InvisibleFrameManager.java:128) ~[ImageFrame-1.8.7.0.jar:?]
	at ImageFrame-1.8.7.0.jar/com.loohp.imageframe.invisibleframe.InvisibleFrameManager.addRecipes(InvisibleFrameManager.java:105) ~[ImageFrame-1.8.7.0.jar:?]
	at ImageFrame-1.8.7.0.jar/com.loohp.imageframe.invisibleframe.InvisibleFrameManager.<init>(InvisibleFrameManager.java:91) ~[ImageFrame-1.8.7.0.jar:?]
	at ImageFrame-1.8.7.0.jar/com.loohp.imageframe.ImageFrame.onEnable(ImageFrame.java:333) ~[ImageFrame-1.8.7.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[paper-api-1.21.9-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.9.jar:1.21.9-38-27f926e]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.9.jar:1.21.9-38-27f926e]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21.9-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.21.9.jar:1.21.9-38-27f926e]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:595) ~[paper-1.21.9.jar:1.21.9-38-27f926e]
	at net.minecraft.server.MinecraftServer.initPostWorld(MinecraftServer.java:554) ~[paper-1.21.9.jar:1.21.9-38-27f926e]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:368) ~[paper-1.21.9.jar:1.21.9-38-27f926e]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1096) ~[paper-1.21.9.jar:1.21.9-38-27f926e]
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:317) ~[paper-1.21.9.jar:1.21.9-38-27f926e]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_21_R6.inventory.CraftItemStack
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:205) ~[paper-api-1.21.9-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:172) ~[paper-api-1.21.9-R0.1-SNAPSHOT.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	... 21 more
[12:56:57] [Server thread/INFO]: [ImageFrame] Disabling ImageFrame v1.8.7.0
[12:56:57] [Server thread/INFO]: [ImageFrame] ImageFrame has been Disabled!
